/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialog;

import gui.MyNotePad;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import javax.swing.DefaultListModel;

/**
 *
 * @author HangNT
 */
public class MyFont extends javax.swing.JDialog {

    MyNotePad mnp = new MyNotePad();
    /**
     * Creates new form MyFont
     */
    private final DefaultListModel<String> listFont;

    public MyFont(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // load all system fonts to list
        jlistFont.setModel(listFont = new DefaultListModel<>());
        Font[] fonts = GraphicsEnvironment.getLocalGraphicsEnvironment().getAllFonts();
        for (Font f : fonts) {
            String family = f.getFamily();
            boolean found = false;
            for (int i = 0; i < listFont.size(); i++) {
                if (listFont.get(i).equals(family)) {
                    found = true;
                }
            }
            if (!found) {
                listFont.addElement(family);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistFont = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListStyle = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListSize = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtViewSample = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Font");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Font style:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Font:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Size:");

        jlistFont.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlistFont.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlistFontValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlistFont);

        jListStyle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jListStyle.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Plain", "Bold", "Italic", "Bold ITalic" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListStyle.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListStyleValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListStyle);

        jListSize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jListSize.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListSize.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListSizeValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListSize);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Sample");

        btnOK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtViewSample.setEditable(false);
        txtViewSample.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtViewSample.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtViewSample.setText("AaBbDdZz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtViewSample)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtViewSample, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancel))
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    public Font getNewText() {
        String family = jlistFont.getSelectedValue();
        int style = 0;
        if (jListStyle.getSelectedIndex() == 1) {
            style = Font.BOLD;
        }
        if (jListStyle.getSelectedIndex() == 2) {
            style = Font.ITALIC;
        }
        if (jListStyle.getSelectedIndex() == 3) {
            style = Font.BOLD + Font.ITALIC;
        }
        if (jListStyle.getSelectedIndex() == 0) {
            style = Font.PLAIN;
        }
        String size = jListSize.getSelectedValue();
        return new Font(family, style, Integer.valueOf(size) );
    }
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void jlistFontValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlistFontValueChanged
        // TODO add your handling code here:
        String family = jlistFont.getSelectedValue();
        Font oldFont = txtViewSample.getFont();
        // apply font moi
        txtViewSample.setFont(new Font(family, oldFont.getStyle(), oldFont.getSize()));
    }//GEN-LAST:event_jlistFontValueChanged

    private void jListStyleValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListStyleValueChanged
        // TODO add your handling code here:
        Font oldFont = txtViewSample.getFont();

        if (jListStyle.getSelectedIndex() == 1) {
            txtViewSample.setFont(new Font(oldFont.getFamily(), Font.BOLD, oldFont.getSize()));
        }
        if (jListStyle.getSelectedIndex() == 2) {
            txtViewSample.setFont(new Font(oldFont.getFamily(), Font.ITALIC, oldFont.getSize()));
        }
        if (jListStyle.getSelectedIndex() == 3) {
            txtViewSample.setFont(new Font(oldFont.getFamily(), (Font.BOLD + Font.ITALIC), oldFont.getSize()));
        }
        if (jListStyle.getSelectedIndex() == 0) {
            txtViewSample.setFont(new Font(oldFont.getFamily(), Font.PLAIN, oldFont.getSize()));
        }

    }//GEN-LAST:event_jListStyleValueChanged

    private void jListSizeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListSizeValueChanged
        // TODO add your handling code here:
        String size = jListSize.getSelectedValue();
        Font oldFont = txtViewSample.getFont();
        // apply font moi
        txtViewSample.setFont(new Font(oldFont.getFamily(), oldFont.getStyle(), Integer.valueOf(size)));
    }//GEN-LAST:event_jListSizeValueChanged

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jListSize;
    private javax.swing.JList<String> jListStyle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> jlistFont;
    private javax.swing.JTextField txtViewSample;
    // End of variables declaration//GEN-END:variables
}
