/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import bo.AuBoPuTiAuBo;
import bo.UsersBo;
import dao.AuthorsDao;
import dao.BooksDao;
import dao.PublishersDao;
import dao.TitleAuthorDao;
import entity.Authors;
import entity.Publishers;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HangNT
 */
public class AddBook extends javax.swing.JDialog {

    /**
     * Creates new form ViewDetailBook
     */
    private DefaultListModel<String> liLeftModel;
    private DefaultListModel<String> liRightModel;
    private DefaultComboBoxModel defaultComboBoxModel;
    private final List<Publishers> listPublisherses;

    private void loadGroupList() {
        jList1.setModel(liLeftModel = new DefaultListModel<>());
        jList2.setModel(liRightModel = new DefaultListModel<>());
        new AuthorsDao().getAll().forEach((object) -> {
            liLeftModel.addElement(((Authors) object).getAu_name());
        });
    }

    private void loadGroupCombox() {
        jComboBox1.setModel(defaultComboBoxModel = new DefaultComboBoxModel<>());
        listPublisherses.forEach((publishers) -> {
            defaultComboBoxModel.addElement(publishers.getPub_name());
        });
        jComboBox1.setSelectedIndex(0);// chon phan tu dau tien la default
    }

    //update gui
    private void updateGui(Locale locale) {
        String url = "resource/languages";
        ResourceBundle rb = ResourceBundle.getBundle(url, locale);
        // de doc
        String addBook = rb.getString("AddBook.AddBook");
        String exit = rb.getString("AddBook.Exit");
        String bookID = rb.getString("AddBook.bookID");
        String bookTitle = rb.getString("AddBook.bookTitle");
        String avaiableAuthors = rb.getString("AddBook.avaiableAuthors");
        String selectedAuthors = rb.getString("AddBook.selectedAuthors");
        String notes = rb.getString("AddBook.notes");
        String save = rb.getString("AddBook.save");
        String clear = rb.getString("AddBook.clear");
        String publisher = rb.getString("Addbook.Publisher");
        String hi = rb.getString("wellcome");
        String authors = rb.getString("AddBook.authors");
        //update data
        txtTitle.setText(addBook);
        txtHi.setText(hi);
        btnExitt1.setText(exit);
        labelLoginAccount11.setText(bookID);
        labelLoginAccount4.setText(bookTitle);
        labelLoginAccount8.setText(publisher);
        labelLoginAccount12.setText(authors);
        labelLoginAccount10.setText(avaiableAuthors);
        labelLoginAccount9.setText(selectedAuthors);
        labelLoginAccount6.setText(notes);
        btnSave.setText(save);
        btnClear.setText(clear);
        txtHi.setText(hi);
        // txtThu.setText(day);

    }

    public AddBook(java.awt.Frame parent, boolean modal, String username, Locale locale) {
        super(parent, modal);
        initComponents();
        txtHiName.setText(username);
        listPublisherses = new PublishersDao().getAll();
        loadGroupList();
        loadGroupCombox();
        updateGui(locale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel4 = new keeptoo.KGradientPanel();
        labelLoginAccount4 = new javax.swing.JLabel();
        txtHiName = new javax.swing.JLabel();
        labelLoginAccount6 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JLabel();
        labelLoginAccount11 = new javax.swing.JLabel();
        labelLoginAccount8 = new javax.swing.JLabel();
        labelLoginAccount9 = new javax.swing.JLabel();
        txtBookTitle = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        txtBookID = new javax.swing.JTextField();
        btnExitt1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        labelLoginAccount10 = new javax.swing.JLabel();
        labelLoginAccount12 = new javax.swing.JLabel();
        btnAfter = new javax.swing.JLabel();
        btnBefore = new javax.swing.JLabel();
        btnSave = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        txtHi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel4.setkEndColor(new java.awt.Color(70, 71, 117));
        kGradientPanel4.setkStartColor(new java.awt.Color(70, 71, 117));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLoginAccount4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount4.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount4.setText("Book Title:");
        kGradientPanel4.add(labelLoginAccount4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 120, 50));

        txtHiName.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        txtHiName.setForeground(new java.awt.Color(255, 255, 255));
        txtHiName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtHiName.setText("---------------");
        txtHiName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel4.add(txtHiName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 160, 30));

        labelLoginAccount6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount6.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount6.setText("Notes:");
        kGradientPanel4.add(labelLoginAccount6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 120, 30));

        txtTitle.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTitle.setText("Add Book");
        kGradientPanel4.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 250, 50));

        labelLoginAccount11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount11.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount11.setText("Book ID:");
        kGradientPanel4.add(labelLoginAccount11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 120, 50));

        labelLoginAccount8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount8.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount8.setText("Publishers:");
        kGradientPanel4.add(labelLoginAccount8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 120, 50));

        labelLoginAccount9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount9.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount9.setText("Selected Authors");
        kGradientPanel4.add(labelLoginAccount9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 190, 30));

        txtBookTitle.setBackground(new java.awt.Color(70, 71, 117));
        txtBookTitle.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        txtBookTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtBookTitle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtBookTitle.setCaretColor(new java.awt.Color(102, 255, 0));
        kGradientPanel4.add(txtBookTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 370, 40));

        jComboBox1.setBackground(new java.awt.Color(51, 153, 255));
        kGradientPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 270, 30));

        txtNotes.setColumns(20);
        txtNotes.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtNotes.setForeground(new java.awt.Color(102, 102, 102));
        txtNotes.setRows(5);
        jScrollPane2.setViewportView(txtNotes);

        kGradientPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 640, 510, 170));

        txtBookID.setBackground(new java.awt.Color(70, 71, 117));
        txtBookID.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        txtBookID.setForeground(new java.awt.Color(255, 255, 255));
        txtBookID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtBookID.setCaretColor(new java.awt.Color(255, 255, 255));
        kGradientPanel4.add(txtBookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 370, 40));

        btnExitt1.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnExitt1.setForeground(new java.awt.Color(255, 255, 255));
        btnExitt1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExitt1.setText("Exit");
        btnExitt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExitt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitt1MouseClicked(evt);
            }
        });
        kGradientPanel4.add(btnExitt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 100, 30));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        kGradientPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 190, 240));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        kGradientPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 190, 240));

        labelLoginAccount10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount10.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount10.setText("Avaliable Authors");
        kGradientPanel4.add(labelLoginAccount10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 170, 30));

        labelLoginAccount12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount12.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount12.setText("Authors:");
        kGradientPanel4.add(labelLoginAccount12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 120, 50));

        btnAfter.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAfter.setForeground(new java.awt.Color(255, 255, 255));
        btnAfter.setText(">>");
        btnAfter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAfter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAfterMouseClicked(evt);
            }
        });
        kGradientPanel4.add(btnAfter, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, -1));

        btnBefore.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBefore.setForeground(new java.awt.Color(255, 255, 255));
        btnBefore.setText("<<");
        btnBefore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBefore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBeforeMouseClicked(evt);
            }
        });
        kGradientPanel4.add(btnBefore, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, -1, -1));

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSave.setText("Save");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        kGradientPanel4.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 830, 100, 30));

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        kGradientPanel4.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 830, 100, 30));

        txtHi.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        txtHi.setForeground(new java.awt.Color(255, 255, 255));
        txtHi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtHi.setText("Welcome");
        txtHi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel4.add(txtHi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private List<String> getSelectIDAuthors() {
        AuthorsDao auDAO = new AuthorsDao();
        List<String> list = new ArrayList();
        for (int i = 0; i < liRightModel.getSize(); i++) {
            list.add(auDAO.getAuthorID(liRightModel.get(i)));

        }
        return list;
    }
    private void btnExitt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitt1MouseClicked
        // TODO add your handling code here:
        int number = new AuBoPuTiAuBo().choiceFunction("Question ", "Do you want to exit?", "Yes", "No", "Cancel");
        new AuBoPuTiAuBo().processFunction(this, number);
    }//GEN-LAST:event_btnExitt1MouseClicked

    private void btnAfterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAfterMouseClicked
        // TODO add your handling code here:
        if (!liRightModel.contains(jList1.getSelectedValue())) {
            liRightModel.addElement(jList1.getSelectedValue());
        } else {
            JOptionPane.showMessageDialog(null, "Author has been added", "Oops", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAfterMouseClicked

    private void btnBeforeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeforeMouseClicked
        // TODO add your handling code here:
        liRightModel.removeElement(jList2.getSelectedValue());
    }//GEN-LAST:event_btnBeforeMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
        String bookID = txtBookID.getText();
        String bookTitle = txtBookTitle.getText();
        String publisher = jComboBox1.getSelectedItem().toString();
        List<String> authorList = getSelectIDAuthors();
        String notes = txtNotes.getText();
        try {
            publisher = new PublishersDao().selectByPublisher(publisher);
            TitleAuthorDao taDAO = new TitleAuthorDao();
            try {
                taDAO.selectTitleAuthor();
            } catch (Exception ex) {
                ex.printStackTrace(System.out);
            }
            if (!new BooksDao().insertBooks(bookID, bookTitle, publisher, notes, "sa")) {
                JOptionPane.showMessageDialog(rootPane, "Cannot add book", "Message", JOptionPane.ERROR_MESSAGE);
            } else {
                //ADD SUCCEED----------------------
                for (String string : authorList) {
                    taDAO.insertTitleAuthor(string, bookID, authorList.indexOf(string) + 1);
                }
                JOptionPane.showMessageDialog(rootPane, "Added", "Message", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        } catch (Exception ex) {
            ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        new UsersBo().clearInput(txtBookID, txtBookTitle);
        txtNotes.setText("");
        jList2.setListData(new String[0]);
    }//GEN-LAST:event_btnClearMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAfter;
    private javax.swing.JLabel btnBefore;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnExitt1;
    private javax.swing.JLabel btnSave;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private javax.swing.JLabel labelLoginAccount10;
    private javax.swing.JLabel labelLoginAccount11;
    private javax.swing.JLabel labelLoginAccount12;
    private javax.swing.JLabel labelLoginAccount4;
    private javax.swing.JLabel labelLoginAccount6;
    private javax.swing.JLabel labelLoginAccount8;
    private javax.swing.JLabel labelLoginAccount9;
    private javax.swing.JTextField txtBookID;
    private javax.swing.JTextField txtBookTitle;
    private javax.swing.JLabel txtHi;
    private javax.swing.JLabel txtHiName;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
