/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import bo.AuBoPuTiAuBo;
import entity.Users;
import java.util.Locale;
import java.util.ResourceBundle;
import view.Home;

/**
 *
 * @author HangNT
 */
public class ViewDetailAccount extends javax.swing.JDialog {

    /**
     * Creates new form ViewDetailAccount
     */
    private final Users users;

    //update gui
    private void updateGui(Locale locale) {
        String url = "resource/languages";
        ResourceBundle rb = ResourceBundle.getBundle(url, locale);
        // de doc
        String viewDetail = rb.getString("ViewDetailAccount.ViewDetail");
        String exit = rb.getString("ViewDetailAccount.exit");
        String username = rb.getString("ViewDetailAccount.username");
        String displayname = rb.getString("ViewDetailAccount.displayname");
        String description = rb.getString("ViewDetailAccount.description");
        String hi = rb.getString("wellcome");

        //update data
        labelLoginAccount7.setText(viewDetail);
        btnExit1.setText(exit);
        labelLoginAccount11.setText(username);
        labelLoginAccount1.setText(displayname);
        labelLoginAccount6.setText(description);
        txtHi.setText(hi);
    }

    public ViewDetailAccount(java.awt.Frame parent, boolean modal, Users users, String username,Locale locale) {
        super(parent, modal);
        initComponents();
        this.users = users;
        txtUsername.setText(users.getUserName());
        txtDisplayName.setText(users.getDisplayName());
        txtDescription.setText(users.getDescription());
        txtHiName.setText(username);
        updateGui(locale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        labelLoginAccount1 = new javax.swing.JLabel();
        txtHiName = new javax.swing.JLabel();
        labelLoginAccount6 = new javax.swing.JLabel();
        txtDisplayName = new javax.swing.JLabel();
        labelLoginAccount7 = new javax.swing.JLabel();
        labelLoginAccount11 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        btnExit1 = new javax.swing.JLabel();
        txtHi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Detail Account");
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(70, 71, 117));
        kGradientPanel1.setkStartColor(new java.awt.Color(70, 71, 117));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLoginAccount1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount1.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount1.setText("Displayname:");
        kGradientPanel1.add(labelLoginAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 120, 50));

        txtHiName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHiName.setForeground(new java.awt.Color(255, 255, 255));
        txtHiName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtHiName.setText("------");
        txtHiName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel1.add(txtHiName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 30));

        labelLoginAccount6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount6.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount6.setText("Description:");
        kGradientPanel1.add(labelLoginAccount6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 120, 50));

        txtDisplayName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDisplayName.setForeground(new java.awt.Color(255, 255, 255));
        txtDisplayName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDisplayName.setText("-----------------------------");
        kGradientPanel1.add(txtDisplayName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 200, 50));

        labelLoginAccount7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelLoginAccount7.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount7.setText("View Detail Account");
        kGradientPanel1.add(labelLoginAccount7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 250, 50));

        labelLoginAccount11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount11.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount11.setText("Username:");
        kGradientPanel1.add(labelLoginAccount11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 170, 50));

        txtDescription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(255, 255, 255));
        txtDescription.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDescription.setText("-----------------------------");
        kGradientPanel1.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 210, 50));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtUsername.setText("-----------------------------");
        kGradientPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 200, 50));

        btnExit1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit1.setForeground(new java.awt.Color(255, 255, 255));
        btnExit1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExit1.setText("Exit");
        btnExit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExit1MouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 50, 30));

        txtHi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHi.setForeground(new java.awt.Color(255, 255, 255));
        txtHi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtHi.setText("Welcome");
        txtHi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel1.add(txtHi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit1MouseClicked
        // TODO add your handling code here:
        int number = new AuBoPuTiAuBo().choiceFunction("Question ", "Do you want to exit?", "Yes", "No", "Cancel");
        new AuBoPuTiAuBo().processFunction(this, number);
    }//GEN-LAST:event_btnExit1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExit1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labelLoginAccount1;
    private javax.swing.JLabel labelLoginAccount11;
    private javax.swing.JLabel labelLoginAccount6;
    private javax.swing.JLabel labelLoginAccount7;
    private javax.swing.JLabel txtDescription;
    private javax.swing.JLabel txtDisplayName;
    private javax.swing.JLabel txtHi;
    private javax.swing.JLabel txtHiName;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
