/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import bo.AuBoPuTiAuBo;
import dao.AuthorsDao;
import dao.BooksDao;
import dao.PublishersDao;
import dao.TitleAuthorDao;
import entity.AuBoPuTiAu;
import entity.Authors;
import entity.Books;
import entity.Publishers;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HangNT
 */
public class ViewDetailBook extends javax.swing.JDialog {

    /**
     * Creates new form ViewDetailBook
     */
    private DefaultComboBoxModel<String> cbModel;
    private DefaultListModel<String> liLeftModel;
    private DefaultListModel<String> liRightModel;
    private Books editBook;
    private AuBoPuTiAu auBoPuTiAu;
    private AuBoPuTiAuBo au;

    public void setEditObject(Books book, AuBoPuTiAu defBook) {
        editBook = book;
        this.auBoPuTiAu = defBook;
    }

    private void loadAuthorName() {
        jList1.setModel(liLeftModel = new DefaultListModel<>());
        jList2.setModel(liRightModel = new DefaultListModel<>());
        try {
            new AuthorsDao().getAll().forEach((object) -> {
                liLeftModel.addElement(((Authors) object).getAu_name());
            });
        } catch (Exception e) {
        }
    }

    private void loadPublisher() {
        jComboBox1.setModel(cbModel = new DefaultComboBoxModel<>());
        new PublishersDao().getAll().forEach((object) -> {
            cbModel.addElement(((Publishers) object).getPub_name());
        });
    }

    public void setSelectedOption() {
        String[] listAu = this.auBoPuTiAu.getAuthors().split(",");
        for (String string : listAu) {
            liRightModel.addElement(string.trim());
        }
        txtBookID.setText(auBoPuTiAu.getTitle_id());
        txtBookTitle.setText(auBoPuTiAu.getTitle());
        cbModel.setSelectedItem(auBoPuTiAu.getPublishers());
        txtNotes.setText(auBoPuTiAu.getNotes());
        System.out.println(auBoPuTiAu);
    }

    private List<String> getSelectIDAuthors() {
        AuthorsDao auDAO = new AuthorsDao();
        List<String> list = new ArrayList();
        for (int i = 0; i < liRightModel.getSize(); i++) {
            list.add(auDAO.getAuthorID(liRightModel.get(i)));
        }
        return list;
    }

    private void updateGui(Locale locale) {
        String url = "resource/languages";
        ResourceBundle rb = ResourceBundle.getBundle(url, locale);
        // de doc
        String viewDetail = rb.getString("ViewDetailAccount.ViewDetail");
        String exit = rb.getString("ViewDetailAccount.exit");
        String bookID = rb.getString("VietDetailBook.bookID");
        String bookTitle = rb.getString("VietDetailBook.bookTitle");
        String publisher = rb.getString("VietDetailBook.Publisher");
        String notes = rb.getString("VietDetailBook.notes");
        String authors = rb.getString("VietDetailBook.authors");
        String remove = rb.getString("VietDetailBook.remove");
        String update = rb.getString("VietDetailBook.update");
        String hi = rb.getString("wellcome");

        //update data
        txtTitle.setText(viewDetail);
        btnExitt1.setText(exit);
        labelLoginAccount11.setText(bookID);
        labelLoginAccount4.setText(bookTitle);
        labelLoginAccount8.setText(publisher);
        labelLoginAccount6.setText(notes);
        labelLoginAccount9.setText(authors);
        btnRemove.setText(remove);
        btnUpdate.setText(update);
        txtHi.setText(hi);
    }

    public ViewDetailBook(java.awt.Frame parent, boolean modal, String username, Locale locale) {
        super(parent, modal);
        initComponents();
        loadAuthorName();
        loadPublisher();
        txtHiName.setText(username);
        updateGui(locale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel4 = new keeptoo.KGradientPanel();
        labelLoginAccount4 = new javax.swing.JLabel();
        txtHiName = new javax.swing.JLabel();
        labelLoginAccount6 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JLabel();
        labelLoginAccount11 = new javax.swing.JLabel();
        txtBookID = new javax.swing.JLabel();
        labelLoginAccount8 = new javax.swing.JLabel();
        labelLoginAccount9 = new javax.swing.JLabel();
        txtBookTitle = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        btnRemove = new javax.swing.JLabel();
        btnRemoveAuthor = new javax.swing.JLabel();
        btnExitt1 = new javax.swing.JLabel();
        txtHi = new javax.swing.JLabel();
        labelLoginAccount10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        labelLoginAccount12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        btnUpdate = new javax.swing.JLabel();
        btnAdd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel4.setkEndColor(new java.awt.Color(70, 71, 117));
        kGradientPanel4.setkStartColor(new java.awt.Color(70, 71, 117));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLoginAccount4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount4.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount4.setText("Book Title:");
        kGradientPanel4.add(labelLoginAccount4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 120, 50));

        txtHiName.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        txtHiName.setForeground(new java.awt.Color(255, 255, 255));
        txtHiName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtHiName.setText("---------------");
        txtHiName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel4.add(txtHiName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 120, 30));

        labelLoginAccount6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount6.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount6.setText("Notes:");
        kGradientPanel4.add(labelLoginAccount6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 120, 50));

        txtTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTitle.setText("View Detail Books");
        kGradientPanel4.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 250, 50));

        labelLoginAccount11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount11.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount11.setText("Book ID:");
        kGradientPanel4.add(labelLoginAccount11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 120, 50));

        txtBookID.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        txtBookID.setForeground(new java.awt.Color(255, 255, 255));
        txtBookID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtBookID.setText("-----------------------------");
        kGradientPanel4.add(txtBookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 210, 50));

        labelLoginAccount8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount8.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount8.setText("Publishers:");
        kGradientPanel4.add(labelLoginAccount8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 120, 50));

        labelLoginAccount9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount9.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount9.setText("Authors:");
        kGradientPanel4.add(labelLoginAccount9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 120, 50));

        txtBookTitle.setBackground(new java.awt.Color(70, 71, 117));
        txtBookTitle.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        txtBookTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtBookTitle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(240, 240, 240)));
        txtBookTitle.setCaretColor(new java.awt.Color(240, 240, 240));
        txtBookTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBookTitleMouseClicked(evt);
            }
        });
        kGradientPanel4.add(txtBookTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 370, 40));

        jComboBox1.setBackground(new java.awt.Color(51, 153, 255));
        kGradientPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 270, 30));

        txtNotes.setColumns(20);
        txtNotes.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtNotes.setForeground(new java.awt.Color(102, 102, 102));
        txtNotes.setRows(5);
        jScrollPane2.setViewportView(txtNotes);

        kGradientPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 670, 490, 190));

        btnRemove.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRemove.setText("Remove");
        btnRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveMouseClicked(evt);
            }
        });
        kGradientPanel4.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 880, 110, 30));

        btnRemoveAuthor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRemoveAuthor.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveAuthor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRemoveAuthor.setText("<<");
        btnRemoveAuthor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemoveAuthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveAuthorMouseClicked(evt);
            }
        });
        kGradientPanel4.add(btnRemoveAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 90, 30));

        btnExitt1.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnExitt1.setForeground(new java.awt.Color(255, 255, 255));
        btnExitt1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExitt1.setText("Exit");
        btnExitt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExitt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitt1MouseClicked(evt);
            }
        });
        kGradientPanel4.add(btnExitt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 50, 30));

        txtHi.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        txtHi.setForeground(new java.awt.Color(255, 255, 255));
        txtHi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtHi.setText("Welcome");
        txtHi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel4.add(txtHi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        labelLoginAccount10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount10.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount10.setText("Avaliable Authors");
        kGradientPanel4.add(labelLoginAccount10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 170, 30));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        kGradientPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 190, 310));

        labelLoginAccount12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLoginAccount12.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAccount12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLoginAccount12.setText("Selected Authors");
        kGradientPanel4.add(labelLoginAccount12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 190, 30));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        kGradientPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 190, 310));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUpdate.setText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        kGradientPanel4.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 880, 100, 30));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdd.setText(">>");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        kGradientPanel4.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBookTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBookTitleMouseClicked
        // TODO add your handling code here:
        txtBookTitle.setText("");
    }//GEN-LAST:event_txtBookTitleMouseClicked

    private void btnRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseClicked
        // TODO add your handling code here:
        txtTitle.setText("Remove");
        int choice = new AuBoPuTiAuBo().choiceFunction("Question ", "Do you remove book?", "Yes", "No");
        switch (choice) {
            case 0: {
                new AuBoPuTiAuBo().removeBooks(auBoPuTiAu);
                this.dispose();
                break;
            }
            case 1: {
                break;
            }
        }
    }//GEN-LAST:event_btnRemoveMouseClicked

    private void btnRemoveAuthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveAuthorMouseClicked
        // TODO add your handling code here:
        liRightModel.removeElement(jList2.getSelectedValue());
    }//GEN-LAST:event_btnRemoveAuthorMouseClicked

    private void btnExitt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitt1MouseClicked
        // TODO add your handling code here:
        int number = new AuBoPuTiAuBo().choiceFunction("Question ", "Do you want to exit?", "Yes", "No", "Cancel");
        new AuBoPuTiAuBo().processFunction(this, number);
    }//GEN-LAST:event_btnExitt1MouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        String bookID = txtBookID.getText();
        String bookTitle = txtBookTitle.getText();
        String publisher = jComboBox1.getSelectedItem().toString();
        List<String> authorList = getSelectIDAuthors();
        String notes = txtNotes.getText();
       try {
            publisher = new PublishersDao().selectByPublisher(publisher);
            TitleAuthorDao taDAO = new TitleAuthorDao();
            try {
                taDAO.selectTitleAuthor();
            } catch (Exception ex) {
            ex.printStackTrace(System.out);
            }
            if (!new BooksDao().updateBooks(bookID, bookTitle, publisher, notes, txtHiName.getText())) {
                JOptionPane.showMessageDialog(rootPane, "Cannot Update", "Message", JOptionPane.ERROR_MESSAGE);
            } else {
                taDAO.delete(bookID);
                for (String string : authorList) {
                    taDAO.insertTitleAuthor(string, bookID, authorList.indexOf(string)+1);
                }
                JOptionPane.showMessageDialog(rootPane, "Updated", "Message", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (HeadlessException | SQLException ex) {
            ex.printStackTrace(System.out);
        }
        this.dispose();
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        if (!liRightModel.contains(jList1.getSelectedValue())) {
            liRightModel.addElement(jList1.getSelectedValue());
        } else {
            JOptionPane.showMessageDialog(null, "Author has been added", "Oops", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnExitt1;
    private javax.swing.JLabel btnRemove;
    private javax.swing.JLabel btnRemoveAuthor;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private javax.swing.JLabel labelLoginAccount10;
    private javax.swing.JLabel labelLoginAccount11;
    private javax.swing.JLabel labelLoginAccount12;
    private javax.swing.JLabel labelLoginAccount4;
    private javax.swing.JLabel labelLoginAccount6;
    private javax.swing.JLabel labelLoginAccount8;
    private javax.swing.JLabel labelLoginAccount9;
    private javax.swing.JLabel txtBookID;
    private javax.swing.JTextField txtBookTitle;
    private javax.swing.JLabel txtHi;
    private javax.swing.JLabel txtHiName;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
