/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import bo.AuBoPuTiAuBo;
import dao.BooksDao;
import dao.TitleAuthorDao;
import entity.AuBoPuTiAu;
import entity.Books;
import entity.TitleAuthor;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import util.Validate;

/**
 *
 * @author HangNT
 */
public class ViewDetailBook extends javax.swing.JDialog {

    /**
     * Creates new form ViewDetailStudent
     */
    private final Locale locale;

    private void updateGui(Locale loc) {
        String url = "resource/languages";
        ResourceBundle rb = ResourceBundle.getBundle(url, loc);
        // de doc
        String viewDetail = rb.getString("VietDetailBook.ViewDetail");
        String exit = rb.getString("VietDetailBook.exit");
        String bookID = rb.getString("VietDetailBook.bookID");
        String bookTitle = rb.getString("VietDetailBook.bookTitle");
        String publisher = rb.getString("VietDetailBook.Publisher");
        String notes = rb.getString("VietDetailBook.notes");
        String authors = rb.getString("VietDetailBook.authors");
        String remove = rb.getString("VietDetailBook.remove");
        String update = rb.getString("VietDetailBook.update");
        String title = rb.getString("viewDetailBook");
        // update
        txtTitile.setText(viewDetail);
        txtExit.setText(exit);
        txtUpdate.setText(update);
        jLabel2.setText(bookID);
        jLabel9.setText(bookTitle);
        jLabel8.setText(publisher);
        jLabel6.setText(notes);
        jLabel7.setText(authors);
        txtRemove.setText(remove);
        this.setTitle(title);
    }
    private final AuBoPuTiAu au;
    private final AuBoPuTiAuBo auBoPuTiAuBo = new AuBoPuTiAuBo();

    public ViewDetailBook(java.awt.Frame parent, boolean modal, String username, AuBoPuTiAu a, Locale locale) {
        super(parent, modal);
        initComponents();
        this.au = a;
        txtAuthors.setText(a.getAuthors());
        txtBookID.setText(a.getTitle_id());
        txtBookTitle.setText(a.getTitle());
        txtNotes.setText(a.getNotes());
        jComboBox1.setSelectedItem(a.getPublishers());
        txtHiName.setText(username);
        this.locale = locale;
        updateGui(locale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("E:\\Form 3-Summer 2019\\Desktop Java Applications(PRJ311)\\JavaSwingOfDuy\\02-Assigment\\ManagementStudent\\img\\bann.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        txtTitile = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBookID = new javax.swing.JTextField();
        txtBookTitle = new javax.swing.JTextField();
        txtAuthors = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtNotes = new javax.swing.JTextArea();
        txtHiName = new javax.swing.JLabel();
        txtExit = new javax.swing.JLabel();
        txtUpdate = new javax.swing.JLabel();
        txtRemove = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Detail Book");

        txtTitile.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtTitile.setForeground(new java.awt.Color(255, 255, 255));
        txtTitile.setText("View Detail");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book ID:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Notes:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Authors:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Publishers:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Book TItle:");

        txtBookID.setEditable(false);
        txtBookID.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N

        txtBookTitle.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N

        txtAuthors.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Algodata Infosystems", "Binnet & Hardley", "Five Lakes Publishing", "GGG&G", "Lucerne Publishing", "New Moon Books", "Ramona Publishers", "Scootney Books" }));

        txtNotes.setColumns(20);
        txtNotes.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtNotes.setRows(5);

        txtHiName.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        txtHiName.setForeground(new java.awt.Color(255, 255, 255));
        txtHiName.setText("----");

        txtExit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtExit.setForeground(new java.awt.Color(255, 255, 255));
        txtExit.setText("Exit");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
        });

        txtUpdate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtUpdate.setForeground(new java.awt.Color(255, 255, 255));
        txtUpdate.setText("Update");
        txtUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUpdateMouseClicked(evt);
            }
        });

        txtRemove.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtRemove.setForeground(new java.awt.Color(255, 255, 255));
        txtRemove.setText("Remove");
        txtRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRemoveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(txtBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTitile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addComponent(txtHiName, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAuthors)
                                .addComponent(txtBookTitle)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(txtRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitile)
                    .addComponent(txtExit)
                    .addComponent(txtHiName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAuthors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRemove)
                    .addComponent(txtUpdate))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUpdateMouseClicked
        txtTitile.setText("Update");
        int number = new AuBoPuTiAuBo().choiceFunction("Update Book", "Do you want to update book title  "
                + this.au.getTitle() + " ?", "Yes", "No");
        switch (number) {
            case 0: {
                String titleName = new Validate().getName(txtBookTitle);
                String publishers = jComboBox1.getSelectedItem().toString();
                String author = new Validate().getName(txtAuthors);
                String notes = txtNotes.getText();
                AuBoPuTiAu au1 = new AuBoPuTiAu(au.getTitle_id(), titleName, publishers, author, notes);
                TitleAuthor titleAuthor = new TitleAuthorDao().getOne(au.getTitle_id());
                boolean testTitleAu = new TitleAuthorDao().update(titleAuthor, au.getTitle_id());
                Books books = new BooksDao().getOne(au.getTitle_id());
                boolean testBooks = new BooksDao().update(books, au.getTitle_id(), titleName);
                if (testBooks && testTitleAu) {
                    JOptionPane.showMessageDialog(null, "Update success");
                } else {
                    JOptionPane.showMessageDialog(null, "Update fail");
                }
                break;
            }
            case 1: {
                break;
            }
        }
        this.dispose();
    }//GEN-LAST:event_txtUpdateMouseClicked

    private void txtRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRemoveMouseClicked
        // TODO add your handling code here:
        txtTitile.setText("Remove");
        int choice = new AuBoPuTiAuBo().choiceFunction("Question ", "Do you remove book?", "Yes", "No");
        switch (choice) {
            case 0: {
                auBoPuTiAuBo.removeBooks(au);
                this.dispose();
                break;
            }
            case 1: {
                break;
            }
        }
    }//GEN-LAST:event_txtRemoveMouseClicked

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        // TODO add your handling code here:
        txtTitile.setText("Exit");
        int number = new AuBoPuTiAuBo().choiceFunction("Question ", "Do  you want to exit?", "Yes", "No", "Cancel");
        new AuBoPuTiAuBo().processFunction(this, number);
    }//GEN-LAST:event_txtExitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAuthors;
    private javax.swing.JTextField txtBookID;
    private javax.swing.JTextField txtBookTitle;
    private javax.swing.JLabel txtExit;
    private javax.swing.JLabel txtHiName;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JLabel txtRemove;
    private javax.swing.JLabel txtTitile;
    private javax.swing.JLabel txtUpdate;
    // End of variables declaration//GEN-END:variables
}
