/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bo.AuBoPuTiAuBo;
import bo.StartBo;
import bo.UsersBo;
import dao.AuBoPuTiAuDao;
import dao.UsersDao;
import entity.AuBoPuTiAu;
import entity.Users;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.TableModel;
import util.FormController;
import view.dialog.AddBook;
import view.dialog.ViewDetailAccount;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     *
     * @param username
     */
    private final AuBoPuTiAuBo auBoPuTiAuBo = new AuBoPuTiAuBo();
    private final List<Users> listUser = new UsersDao().getAll();
    private final UsersBo usersBo = new UsersBo();
    private final List<AuBoPuTiAu> listSearch = new ArrayList<>();
    private final Locale locale;

    //update gui
    private void updateGui(Locale locale) {
        String url = "resource/languages";
        ResourceBundle rb = ResourceBundle.getBundle(url, locale);
        // de doc
        String home = rb.getString("home.home");
        String showAccount = rb.getString("home.ShowAccount");
        String exit = rb.getString("home.exit");
        String showBook = rb.getString("home.ShowBook");
        String add = rb.getString("home.AddBook");
        String search = rb.getString("home.Search");
        String searchBy = rb.getString("search.searchBy");
        String key = rb.getString("search.key");
        String hi = rb.getString("wellcome");
        String logout = rb.getString("home.logout");

        //update data
        btnHome.setText(home);
        btnShowAccount.setText(showAccount);
        btnShowBooks.setText(showBook);
        btnSearchBooks.setText(search);
        btnExit.setText(exit);
        btnAddBooks.setText(add);
        labelKey.setText(key);
        labelSearchBy.setText(searchBy);
        txtHi.setText(hi);
        btnLogout.setText(logout);
    }

    WindowAdapter getAction = new WindowAdapter() {
        @Override
        public void windowClosed(WindowEvent e) {
            new AuBoPuTiAuBo().displayTable(tableBooks, new AuBoPuTiAuDao().getAll());
        }

    };

    public Home(String username) {
        initComponents();
        resetColor(new JPanel[]{brn_1, brn_2, brn_3, brn_4, brn_5, brn_8, brn_9},
                new JPanel[]{ind_1, ind_2, ind_3, ind_4, ind_5, ind_8, ind_9});
        txtHiName.setText(username);
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        usersBo.hideSomeThings(jComboBox1, txtKey, labelKey, labelSearchButton,
                labelSearchBy);

        // get month and year
        String month = new SimpleDateFormat("MMMMMMMMM").format(Calendar.getInstance().getTime());
        int year = Calendar.getInstance().get(Calendar.YEAR);

        //get day and thu
        Calendar cal = Calendar.getInstance();
        int numberInWeek = cal.get(Calendar.DAY_OF_WEEK);
        String dayInWeek = new StartBo().getMondayToSunday(numberInWeek);
        int dayOfMonth = cal.get(Calendar.DAY_OF_MONTH);
        String day = String.valueOf(dayOfMonth);

        txtYear.setText(dayInWeek + "   " + day + "   " + month + "   " + String.valueOf(year));
        Locale locale = new StartBo().choiceLanguage(auBoPuTiAuBo);
        this.locale = locale;
        updateGui(this.locale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_pane = new javax.swing.JPanel();
        brn_4 = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        btnSearchBooks = new javax.swing.JLabel();
        brn_2 = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        btnShowAccount = new javax.swing.JLabel();
        brn_1 = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        brn_3 = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        btnShowBooks = new javax.swing.JLabel();
        brn_5 = new javax.swing.JPanel();
        ind_5 = new javax.swing.JPanel();
        btnAddBooks = new javax.swing.JLabel();
        brn_8 = new javax.swing.JPanel();
        ind_8 = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        brn_9 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        ind_9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelSearchButton = new javax.swing.JLabel();
        labelSearchBy = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        labelKey = new javax.swing.JLabel();
        txtKey = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtHi = new javax.swing.JLabel();
        txtHiName = new javax.swing.JLabel();
        txtYear = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBooks = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAccount = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brn_4.setBackground(new java.awt.Color(23, 35, 51));

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        btnSearchBooks.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSearchBooks.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearchBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search-3-16.png"))); // NOI18N
        btnSearchBooks.setText("Search Books");
        btnSearchBooks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchBooksMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brn_4Layout = new javax.swing.GroupLayout(brn_4);
        brn_4.setLayout(brn_4Layout);
        brn_4Layout.setHorizontalGroup(
            brn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_4Layout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(brn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(brn_4Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(btnSearchBooks, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addGap(4, 4, 4)))
        );
        brn_4Layout.setVerticalGroup(
            brn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_4Layout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(brn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(brn_4Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(btnSearchBooks)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        side_pane.add(brn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 120, -1));

        brn_2.setBackground(new java.awt.Color(23, 35, 51));

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        btnShowAccount.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnShowAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnShowAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnShowAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info-16.png"))); // NOI18N
        btnShowAccount.setText("Show Account");
        btnShowAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowAccountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brn_2Layout = new javax.swing.GroupLayout(brn_2);
        brn_2.setLayout(brn_2Layout);
        brn_2Layout.setHorizontalGroup(
            brn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_2Layout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(brn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(brn_2Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(btnShowAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addGap(4, 4, 4)))
        );
        brn_2Layout.setVerticalGroup(
            brn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_2Layout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(brn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(brn_2Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(btnShowAccount)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        side_pane.add(brn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 120, -1));

        brn_1.setBackground(new java.awt.Color(23, 35, 51));

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        btnHome.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home-5-16.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brn_1Layout = new javax.swing.GroupLayout(brn_1);
        brn_1.setLayout(brn_1Layout);
        brn_1Layout.setHorizontalGroup(
            brn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_1Layout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(brn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(brn_1Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addGap(4, 4, 4)))
        );
        brn_1Layout.setVerticalGroup(
            brn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_1Layout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(brn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(brn_1Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(btnHome)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        side_pane.add(brn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 120, -1));

        brn_3.setBackground(new java.awt.Color(23, 35, 51));

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        btnShowBooks.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnShowBooks.setForeground(new java.awt.Color(255, 255, 255));
        btnShowBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnShowBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info-16.png"))); // NOI18N
        btnShowBooks.setText("Show Books");
        btnShowBooks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowBooksMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brn_3Layout = new javax.swing.GroupLayout(brn_3);
        brn_3.setLayout(brn_3Layout);
        brn_3Layout.setHorizontalGroup(
            brn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_3Layout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(brn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(brn_3Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(btnShowBooks, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addGap(4, 4, 4)))
        );
        brn_3Layout.setVerticalGroup(
            brn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_3Layout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(brn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(brn_3Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(btnShowBooks)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        side_pane.add(brn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 120, -1));

        brn_5.setBackground(new java.awt.Color(23, 35, 51));

        ind_5.setOpaque(false);
        ind_5.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_5Layout = new javax.swing.GroupLayout(ind_5);
        ind_5.setLayout(ind_5Layout);
        ind_5Layout.setHorizontalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_5Layout.setVerticalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        btnAddBooks.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAddBooks.setForeground(new java.awt.Color(255, 255, 255));
        btnAddBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-16.png"))); // NOI18N
        btnAddBooks.setText("Add Books");
        btnAddBooks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddBooksMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brn_5Layout = new javax.swing.GroupLayout(brn_5);
        brn_5.setLayout(brn_5Layout);
        brn_5Layout.setHorizontalGroup(
            brn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_5Layout.createSequentialGroup()
                .addComponent(ind_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(brn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(brn_5Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(btnAddBooks, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addGap(4, 4, 4)))
        );
        brn_5Layout.setVerticalGroup(
            brn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_5Layout.createSequentialGroup()
                .addComponent(ind_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(brn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(brn_5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnAddBooks)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        side_pane.add(brn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 120, -1));

        brn_8.setBackground(new java.awt.Color(23, 35, 51));

        ind_8.setOpaque(false);
        ind_8.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_8Layout = new javax.swing.GroupLayout(ind_8);
        ind_8.setLayout(ind_8Layout);
        ind_8Layout.setHorizontalGroup(
            ind_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_8Layout.setVerticalGroup(
            ind_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit-16.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brn_8Layout = new javax.swing.GroupLayout(brn_8);
        brn_8.setLayout(brn_8Layout);
        brn_8Layout.setHorizontalGroup(
            brn_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_8Layout.createSequentialGroup()
                .addComponent(ind_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(brn_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(brn_8Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addGap(4, 4, 4)))
        );
        brn_8Layout.setVerticalGroup(
            brn_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_8Layout.createSequentialGroup()
                .addComponent(ind_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(brn_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(brn_8Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(btnExit)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        side_pane.add(brn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 120, -1));

        brn_9.setBackground(new java.awt.Color(23, 35, 51));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout-16.png"))); // NOI18N
        btnLogout.setText("Log out");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        ind_9.setOpaque(false);
        ind_9.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_9Layout = new javax.swing.GroupLayout(ind_9);
        ind_9.setLayout(ind_9Layout);
        ind_9Layout.setHorizontalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_9Layout.setVerticalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout brn_9Layout = new javax.swing.GroupLayout(brn_9);
        brn_9.setLayout(brn_9Layout);
        brn_9Layout.setHorizontalGroup(
            brn_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_9Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(brn_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(brn_9Layout.createSequentialGroup()
                    .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 110, Short.MAX_VALUE)))
        );
        brn_9Layout.setVerticalGroup(
            brn_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brn_9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(brn_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(brn_9Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        side_pane.add(brn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 120, 50));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 120, 570));

        jPanel2.setBackground(new java.awt.Color(70, 71, 117));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Search_18px.png"))); // NOI18N
        labelSearchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSearchButtonMouseClicked(evt);
            }
        });
        jPanel2.add(labelSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1098, 44, -1, 20));

        labelSearchBy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelSearchBy.setForeground(new java.awt.Color(255, 255, 255));
        labelSearchBy.setText("Search by");
        jPanel2.add(labelSearchBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 34, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Book ID", "Book Title", "Publisher Name", "Author Name", "Notes", "All" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 29, 239, 34));

        labelKey.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelKey.setForeground(new java.awt.Color(255, 255, 255));
        labelKey.setText("Enter key:");
        jPanel2.add(labelKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 34, -1, -1));

        txtKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKeyMouseClicked(evt);
            }
        });
        jPanel2.add(txtKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 33, 314, 31));

        jPanel4.setBackground(new java.awt.Color(70, 71, 117));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/61129323_375240960005336_1316931930385547264_n.jpg"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 86, 90));

        txtHi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHi.setForeground(new java.awt.Color(255, 255, 255));
        txtHi.setText("Wellcome ");
        jPanel4.add(txtHi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 70, 30));

        txtHiName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHiName.setForeground(new java.awt.Color(255, 255, 255));
        txtHiName.setText("HangNT");
        jPanel4.add(txtHiName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 130, 30));

        txtYear.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtYear.setForeground(new java.awt.Color(255, 255, 255));
        txtYear.setText("-----");
        txtYear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 200, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 100));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tableBooks.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tableBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Book ID", "Book Title", "Publishers", "Authors", "Notes"
            }
        ));
        tableBooks.setGridColor(new java.awt.Color(255, 255, 255));
        tableBooks.setRowHeight(22);
        tableBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBooksMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableBooks);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1040, 480));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tableAccount.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tableAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Username", "Displayname", "Description"
            }
        ));
        tableAccount.setGridColor(new java.awt.Color(255, 255, 255));
        tableAccount.setRowHeight(22);
        tableAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAccountMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAccount);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 95, 1040, 480));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 1040, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int xx, xy;
    private void txtKeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKeyMouseClicked
        // TODO add your handling code here:
        txtKey.setText("");
    }//GEN-LAST:event_txtKeyMouseClicked

    private void labelSearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSearchButtonMouseClicked
        // TODO add your handling code here:
        new AuBoPuTiAuBo().showResult(tableBooks, listSearch, txtKey.getText(),
                jComboBox1.getSelectedIndex());
        if (tableBooks.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Not found "
                    + txtKey.getText(), "Message", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_labelSearchButtonMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        usersBo.hideSomeThings(jComboBox1, txtKey, labelKey, labelSearchButton, 
                labelSearchBy);
        ind_1.setOpaque(true);
        setColor(brn_1);
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        resetColor(new JPanel[]{brn_2, brn_3, brn_4, brn_5, brn_8, brn_9},
                new JPanel[]{ind_2, ind_3, ind_4, ind_5, ind_8, ind_9});
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnShowAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowAccountMouseClicked
        // TODO add your handling code here:
        usersBo.hideSomeThings(jComboBox1, txtKey, labelKey, labelSearchButton, 
                labelSearchBy);
        ind_2.setOpaque(true);
        setColor(brn_2);
        jPanel6.setVisible(true);
        jScrollPane1.setVisible(true);
        jScrollPane2.setVisible(false);
        usersBo.displayTable(tableAccount, listUser);
        resetColor(new JPanel[]{brn_1, brn_3, brn_4, brn_5, brn_8, brn_9},
                new JPanel[]{ind_1, ind_3, ind_4, ind_5, ind_8, ind_9});
    }//GEN-LAST:event_btnShowAccountMouseClicked

    private void btnShowBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowBooksMouseClicked
        // TODO add your handling code here:
        usersBo.hideSomeThings(jComboBox1, txtKey, labelKey, labelSearchButton,
                labelSearchBy);
        ind_3.setOpaque(true);
        setColor(brn_3);
        jPanel6.setVisible(true);
        jScrollPane2.setVisible(true);
        jScrollPane1.setVisible(false);
        List<AuBoPuTiAu> lists = new AuBoPuTiAuDao().getAll();
        auBoPuTiAuBo.displayTable(tableBooks, lists);
        resetColor(new JPanel[]{brn_1, brn_2, brn_4, brn_5, brn_8, brn_9},
                new JPanel[]{ind_1, ind_2, ind_4, ind_5, ind_8, ind_9});
    }//GEN-LAST:event_btnShowBooksMouseClicked

    private void btnSearchBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchBooksMouseClicked
        // TODO add your handling code here:
        auBoPuTiAuBo.removeTable(tableBooks);
        usersBo.showSomeThings(jComboBox1, txtKey, labelKey, labelSearchButton, 
                labelSearchBy);
        ind_4.setOpaque(true);
        setColor(brn_4);
        resetColor(new JPanel[]{brn_1, brn_2, brn_3, brn_5, brn_8, brn_9},
                new JPanel[]{ind_1, ind_2, ind_3, ind_5, ind_8, ind_9});
        jPanel6.setVisible(true);
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(true);
    }//GEN-LAST:event_btnSearchBooksMouseClicked

    private void btnAddBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBooksMouseClicked
        // TODO add your handling code here:      
        usersBo.hideSomeThings(jComboBox1, txtKey, labelKey, labelSearchButton, 
                labelSearchBy);
        ind_5.setOpaque(true);
        setColor(brn_5);
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        resetColor(new JPanel[]{brn_1, brn_2, brn_3, brn_4, brn_8, brn_9},
                new JPanel[]{ind_1, ind_2, ind_3, ind_4, ind_8, ind_9});
        AddBook addBook = new AddBook(this, true, txtHiName.getText(), this.locale);
        addBook.addWindowListener(getAction);
        FormController.show(addBook);
    }//GEN-LAST:event_btnAddBooksMouseClicked


    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        usersBo.hideSomeThings(jComboBox1, txtKey, labelKey, labelSearchButton,
                labelSearchBy);
        ind_8.setOpaque(true);
        setColor(brn_8);
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        resetColor(new JPanel[]{brn_1, brn_2, brn_3, brn_4, brn_5, brn_9},
                new JPanel[]{ind_1, ind_2, ind_3, ind_4, ind_5, ind_9});
        int number = new AuBoPuTiAuBo().choiceFunction("Question ",
                "Do you want to close program?", "Yes", "No", "Cancel");
        new AuBoPuTiAuBo().processFunction(this, number);
    }//GEN-LAST:event_btnExitMouseClicked

    private void tableBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBooksMouseClicked
        // TODO add your handling code here:
        auBoPuTiAuBo.searchBook(tableBooks, txtHiName.getText(), this.locale);
    }//GEN-LAST:event_tableBooksMouseClicked

    private void tableAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAccountMouseClicked
        // TODO add your handling code here:
        int index = tableAccount.getSelectedRow();
        TableModel model = tableAccount.getModel();
        String rollNumber = model.getValueAt(index, 1).toString().trim();
        Users users = new UsersDao().getOne(rollNumber);
        FormController.show(new ViewDetailAccount(this, true, users,
                txtHiName.getText(), this.locale));
    }//GEN-LAST:event_tableAccountMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        auBoPuTiAuBo.hideSomeThings(jComboBox1, txtKey, labelKey
                ,labelSearchButton, labelSearchBy);
        setColor(brn_9);
        resetColor(new JPanel[]{brn_1, brn_2, brn_3, brn_4, brn_5, brn_8},
                new JPanel[]{ind_1, ind_2, ind_3, ind_4, ind_5, ind_8});
        int number = auBoPuTiAuBo.choiceFunction("Question ",
                "Do you want to log out?", "Yes", "No");
        switch (number) {
            case 0: {
                FormController.show(new LoginAccount());
                this.dispose();
                break;
            }
            case 1: {
                break;
            }
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void setColor(JPanel pane) {
        pane.setBackground(new Color(41, 57, 80));
    }

    private void resetColor(JPanel[] pane, JPanel[] indicators) {
        for (JPanel pane1 : pane) {
            pane1.setBackground(new Color(23, 35, 51));
        }
        for (JPanel indicator : indicators) {
            indicator.setOpaque(false);
        }

    }

    public static void main(String[] args) {
        FormController.show(new Home(" Hang Nguyen"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel brn_1;
    private javax.swing.JPanel brn_2;
    private javax.swing.JPanel brn_3;
    private javax.swing.JPanel brn_4;
    private javax.swing.JPanel brn_5;
    private javax.swing.JPanel brn_8;
    private javax.swing.JPanel brn_9;
    private javax.swing.JLabel btnAddBooks;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnSearchBooks;
    private javax.swing.JLabel btnShowAccount;
    private javax.swing.JLabel btnShowBooks;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_5;
    private javax.swing.JPanel ind_8;
    private javax.swing.JPanel ind_9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelKey;
    private javax.swing.JLabel labelSearchButton;
    private javax.swing.JLabel labelSearchBy;
    private javax.swing.JPanel side_pane;
    private javax.swing.JTable tableAccount;
    private javax.swing.JTable tableBooks;
    private javax.swing.JLabel txtHi;
    private javax.swing.JLabel txtHiName;
    private javax.swing.JTextField txtKey;
    private javax.swing.JLabel txtYear;
    // End of variables declaration//GEN-END:variables
}
